version: '2.1'
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=ktoreasydb
      - MYSQL_USER=ktoreasyuser
      - MYSQL_PASSWORD=ktoreasypassword
    ports:
      - "3308:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      timeout: 3s
      retries: 5

  backend:
    build: .
    mem_limit: 300m
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ENVIRONMENT=dev
    restart: always
    ports:
      - "3510:3500"

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "3570:9090"
    volumes:
      - ./monitoring:/etc/prometheus/
    links:
      - backend

  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - "3000:3000"
    user: "104"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    links:
      - backend
      - prometheus
